### ISSUE TITLE
Can you share code please 

### ISSUE THREAD

**Issue by saikumarkethi** [TuanBC/memae-tf#1]

**Comment by TuanBC** [comment]
In this repo, I tried to translate the original Pytorch code into TF2. The original MemoryUnit(nn.Module) was translated into MemoryUnit(Layer). You can use it as followed.

Note: the MemoryUnit can only deal with vector, thus I flattened the input matrix here. If you need to apply it to images or higher dimensioned input, you need a MemModule, which I haven't finished translating here.

```
x_input = Input(shape=[28,28,1])

x = Flatten()(x_input)

x = Dense(256, activation='relu')(x)
x = Dense(64, activation='relu')(x)

x = MemoryUnit(100)(x)

x = Dense(256, activation='relu')(x)
x = Dense(784, activation='relu')(x)

x = Reshape((28,28,1))(x)


model_2 = Model(x_input, x)
model_2.summary()
```
